### ISSUE TITLE
geonames-ws-client 1.1.20-2 missing

### ISSUE THREAD

**Issue by ghost** [SemanticComputing/saha#4]
I ran the command `mvn compile` with Maven and got this error:

`
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building smetana 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://www.seco.tkk.fi/software/maven/org/geonames/geonames-ws-client/1.1.10-2/geonames-ws-client-1.1.10-2.pom
Downloading: http://repository.codehaus.org/org/geonames/geonames-ws-client/1.1.10-2/geonames-ws-client-1.1.10-2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.095 s
[INFO] Finished at: 2018-02-09T10:15:46+02:00
[INFO] Final Memory: 11M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project smetana: Could not resolve dependencies for project fi.seco:smetana:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.geonames:geonames-ws-client:jar:1.1.10-2: Failed to read artifact descriptor for org.geonames:geonames-ws-client:jar:1.1.10-2: Could not transfer artifact org.geonames:geonames-ws-client:pom:1.1.10-2 from/to codehaus (http://repository.codehaus.org): repository.codehaus.org: Name or service not known: Unknown host repository.codehaus.org: Name or service not known -> [Help 1]
`

@jiemakel was the org.geonames:geonames-ws-client:jar:1.1.10-2 previously in the www.seco.tkk.fi/software/maven repository? I was wondering if it had any custom modifications in it as it has that -2 suffix in the version?

**Comment by jiemakel** [comment]
Probably not, but can't remember. This is needed for the geonames autocompletion, if that works then probably not :).

**Comment by ghost** [comment]
The geonames autocompletion looks like it works the same way as before so let's close this.

**Comment by jiemakel** [comment]
Did you btw check with a place that wasn't already in the project? It pulls in info then that it doesn't otherwise.

**Comment by ghost** [comment]
Yes, I did.
